import { expect, test } from '@playwright/test'

test('friends can create a trip, choose dates, and join with its code', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /Find the dates/i })).toBeVisible()
  const favicon = await page.locator('link[rel="icon"]').getAttribute('href')
  expect(favicon).toBe('./favicon.svg')

  await page.getByRole('button', { name: /Start a new trip/i }).click()
  await page.getByLabel('Trip name').fill('Caribbean long weekend')
  await page.getByRole('textbox', { name: 'Destination 1', exact: true }).fill('Cartagena')
  await page.getByRole('button', { name: /Add another destination/i }).click()
  await page.getByRole('textbox', { name: 'Destination 2', exact: true }).fill('Minca')
  await page.getByLabel('Your name').fill('Dani')
  await page.getByRole('button', { name: /Create the trip/i }).click()

  await expect(page.getByRole('heading', { name: 'Caribbean long weekend' })).toBeVisible()
  await expect(page.getByText('Cartagena')).toBeVisible()
  await expect(page.getByText('Minca')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Rename trip' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Cancel trip' })).toBeVisible()

  await page.getByRole('button', { name: 'Rename trip' }).click()
  await page.getByLabel('Trip name').fill('Caribbean coast loop')
  await page.getByRole('button', { name: /Save new name/i }).click()
  await expect(page.getByRole('heading', { name: 'Caribbean coast loop' })).toBeVisible()

  await page.getByRole('button', { name: /Add a note/i }).click()
  await page.getByLabel('Title').fill('Rooftop stay in Getsemaní')
  await page.getByLabel(/Link/).fill('airbnb.com/rooms/123')
  await page.getByLabel(/Note/).fill('Sleeps six and has free cancellation.')
  await page.getByRole('button', { name: /Pin it/i }).click()
  await expect(page.getByRole('heading', { name: 'Rooftop stay in Getsemaní' })).toBeVisible()
  await expect(page.getByRole('link', { name: /airbnb.com/i })).toHaveAttribute('href', 'https://airbnb.com/rooms/123')

  const availableDates = page.locator('button.date-cell:not([disabled])')
  const dateLabels = await availableDates.evaluateAll((buttons) => buttons.map((button) => button.getAttribute('aria-label')))
  expect(dateLabels[2]).not.toBe(dateLabels[3])
  await availableDates.nth(2).click()
  await expect(page.locator('.save-bar')).toContainText('1 date selected')
  await availableDates.nth(3).click()
  await expect(page.locator('.save-bar')).toContainText('2 dates selected')
  await page.getByRole('button', { name: /Save my dates/i }).click()
  await expect(page.getByRole('button', { name: /Saved/i })).toBeVisible()

  const tripCode = await page.locator('.code-chip strong').textContent()
  expect(tripCode).toMatch(/^[A-Z0-9]{6}$/)
  const tripUrl = page.url()

  await page.evaluate(() => {
    localStorage.removeItem('palsplan:members')
    localStorage.removeItem('palsplan:creators')
  })
  await page.goto(tripUrl)
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Have you been here before?' })).toBeVisible()
  await expect(page.locator('.traveler-option').filter({ hasText: 'Dani' })).toContainText('2 saved dates')
  await page.locator('.traveler-option').filter({ hasText: 'Dani' }).click()
  await expect(page.locator('.save-bar')).toContainText('2 dates selected')
  await expect(page.getByText('1 traveler')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Rename trip' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Cancel trip' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Rooftop stay in Getsemaní' })).toBeVisible()

  await page.evaluate(() => localStorage.removeItem('palsplan:members'))
  await page.goto(tripUrl)
  await page.getByRole('button', { name: /I’m new here/i }).click()
  await page.getByLabel('New traveler name').fill('Dani')
  await page.getByRole('button', { name: /Add me/i }).click()
  await expect(page.getByText(/traveler already exists/i)).toBeVisible()
  await page.getByLabel('New traveler name').fill('Maya')
  await page.getByRole('button', { name: /Add me/i }).click()
  await expect(page.getByText('2 travelers')).toBeVisible()
  await expect(page.getByText('Maya', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Rooftop stay in Getsemaní' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Rename trip' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Cancel trip' })).toHaveCount(0)
})

test('invalid invite code has a useful error', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Trip code').fill('ABC123')
  await page.getByRole('button', { name: /Join trip/i }).click()
  await expect(page.getByText(/couldn’t find that trip/i)).toBeVisible()
})

test('only the creator can cancel a trip', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Start a new trip/i }).click()
  await page.getByLabel('Trip name').fill('Plan to cancel')
  await page.getByLabel('Your name').fill('Creator')
  await page.getByRole('button', { name: /Create the trip/i }).click()
  const tripCode = await page.locator('.code-chip strong').textContent()

  await page.getByRole('button', { name: 'Cancel trip' }).click()
  await page.getByLabel(/Type “Plan to cancel”/).fill('Plan to cancel')
  await page.getByRole('button', { name: /Cancel trip permanently/i }).click()
  await expect(page.getByRole('heading', { name: /Find the dates/i })).toBeVisible()

  await page.getByLabel('Trip code').fill(tripCode!)
  await page.getByRole('button', { name: /Join trip/i }).click()
  await expect(page.getByText(/couldn’t find that trip/i)).toBeVisible()
})
